name: speech-emotion-recognition
dependencies:
  - python=3.8
  - pip
  - pip:
    - streamlit==1.13.0
    - librosa==0.8.1
    - numpy==1.21.0
    - pandas==1.3.2
    - joblib==1.0.1
    - scikit-learn==0.24.2
